[package]
name = "zage"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive", "env", "string", "unicode"] }
color-eyre = "0.6"
thiserror = "2"
miette = { version = "7", features = ["fancy"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
human-panic = "2.0"
clap-config-file = "0.5.0"
uuid = { version = "1.16.0", features = ["fast-rng", "std", "v7"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9"
bstr = { version = "1.9.0", features = ["serde"] }
rusqlite = { version = "0.34.0", features = ["bundled", "load_extension"] }
exemplar = "0.34.0"
dirs = "6.0.0"
bytes = "1.10.1"
rand = "0.9.1"
uzers = "0.12"
hostname = "0.4.1"
itertools = "0.14.0"
jiff = "0.2.13"
candle-core = { version = "0.9.1", default-features = false }
candle-nn = { version = "0.9.1", default-features = false }
csv = "1.2"
shell-words = "1.1.0"
hf-hub = "0.4.2"
tokenizers = "0.21"
sqlite-vec = "0.1.6"

# Thread pool for socket server
threadpool = "1.8.1"

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))'.dependencies]
candle-core = { version = "0.9.1", default-features = false, features = [
  "accelerate",
  "metal",
] }
candle-nn = { version = "0.9.1", default-features = false, features = [
  "accelerate",
  "metal",
] }

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
cudarc = ["candle-core/cudarc"]
cudnn = ["candle-core/cudnn", "candle-nn/cudnn"]
mkl = ["candle-core/mkl", "candle-nn/mkl"]

[dev-dependencies]
tempfile = "3.10.1"
assert_cmd = "2"
predicates = "3"
color-backtrace = "0.7.0"
ctor = "0.4"

[[bin]]
name = "simulate"
path = "src/bin/simulate.rs"

[[bin]]
name = "simulate_context"
path = "src/bin/simulate_context.rs"

[[bin]]
name = "simulate_workflow"
path = "src/bin/simulate_workflow.rs"

[[bin]]
name = "test_embedding_client"
path = "src/bin/test_embedding_client.rs"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
